version: '3.8'

services:
  backend:
    container_name: java_b_api
    build:
      context: TP1_2/simple-api-student-main
      dockerfile: Dockerfile
    networks:
      - tp1
    depends_on:
      - database
    environment:
      - POSTGRES_NAME=db:5432
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd

  database:
    container_name: db
    build: TP1
    networks:
      - tp1
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=db:5432
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd

  httpd:
    build: TP1_http
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - tp1
    depends_on:
      - frontend


  frontend:
    container_name: front
    build:
      context: ./devops-front-main
    networks:
      - tp1
    depends_on:
      - backend

networks:
  tp1:
volumes:
  db:
