- hosts: all
  gather_facts: false
  become: true

  roles:
    - ./roles/docker
    - ./roles/create-network
    - ./roles/launch-database
    - ./roles/launch-app
    - ./roles/launch-proxy
    - ./roles/launch-front
